# Generated by Django 6.1 on 2026-08-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('ville', models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaoundé'), ('autre', 'Autre')], max_length=30)),
                ('domaine_interet', models.CharField(choices=[('web', 'Développement Web & Mobile'), ('data', 'Data Science & Intelligence Artificielle'), ('networks', 'Réseaux & Sécurité'), ('design', 'Design UI/UX')], max_length=30)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
